version: '2'

services:
  haproxy:
    container_name: haproxy
    image: haproxy:latest
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - 80:80
      - 9000:9000
    links:
      - front_http_1_A
      - front_http_1_B
      - front_http_2_A
      - front_http_2_B
