version: '2'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    links:
      - front_http_1_A
      - front_http_1_B
      - front_http_2_A
      - front_http_2_B
