version: '2'

services:
  traefik:
    container_name: traefik
    image: traefik:latest
    volumes:
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
    ports:
      - 80:80
      - 9000:9000
    links:
      - front_http_1_A
      - front_http_1_B
      - front_http_2_A
      - front_http_2_B
